// Generated by gen_body_mma.py (agents/moe8/body). Do not edit by hand.
// Swap-AB: A = weights [2 K-chunks][128 rows][128 B] (SW128), B = tokens, 8-row SW128 atoms.
// A desc: +((kk/4)*16384 + (kk%4)*32)/16 (FC2 k-steps 4, 5 sit at +64 B: chunk 1 starts at k = 64);
// B desc: +((kk/4)*1024 + (kk%4)*32)/16.
// FC1: a_sf_id = b_sf_id = kk%4; SF TMEM += (kk/4)*4; token-SF images 2 x 128 B (desc +8).
// live == 0: dry run (nothing is issued; warms the instruction cache).
// FC2: a_sf_id = kk%4 (SFA += (kk/4)*4); h SFB per FC1 tile r = kk/2: TMEM base + 4r, b_sf_id = kk%2;
//      the 3 h-SF images sit at 128 B stride (desc +8).
#pragma once
#include <cstdint>
namespace tc {
__device__ __forceinline__ void fc1_stage(uint32_t d, uint64_t adesc, uint64_t bdesc, uint32_t idesc, uint32_t sfa,
    uint64_t sfa_src, uint32_t sfb, uint64_t sfb_src, uint32_t copy_sfb, uint32_t accum, uint32_t bar_empty,
    uint32_t bar_acc, uint32_t live = 1u) {
  asm volatile(
      "{\n\t.reg .pred e, p0, pt, pc, pa, pl;\n\t.reg .b64 s1, s2;\n\t.reg .b32 i<4>, u1, v1;\n\t"
      ".reg .b64 xa<8>, xb<8>;\n\t"
      "elect.sync _|e, 0xffffffff;\n\tsetp.ne.b32 pl, %12, 0;\n\tand.pred e, e, pl;\n\t"
      "setp.eq.b32 pt, 0, 0;\n\tsetp.ne.b32 pc, %8, 0;\n\tsetp.ne.b32 pa, %11, 0;\n\tsetp.ne.b32 p0, %9, 0;\n\t"
      "and.pred pc, pc, e;\n\tand.pred pa, pa, e;\n\t"
      "or.b32 i0, %3, 0;\n\t"
      "or.b32 i1, %3, 536870928;\n\t"
      "or.b32 i2, %3, 1073741856;\n\t"
      "or.b32 i3, %3, 1610612784;\n\t"
      "add.s64 s1, %5, 32;\n\tadd.s64 s2, %7, 8;\n\tadd.u32 u1, %4, 4;\n\tadd.u32 v1, %6, 4;\n\t"
      "@pc tcgen05.cp.cta_group::1.32x128b.warpx4 [%6], %7;\n\t"
      "@pc tcgen05.cp.cta_group::1.32x128b.warpx4 [v1], s2;\n\t"
      "@e tcgen05.cp.cta_group::1.32x128b.warpx4 [%4], %5;\n\t"
      "@e tcgen05.cp.cta_group::1.32x128b.warpx4 [u1], s1;\n\t"
      "add.s64 xa0, %1, 0;\n\tadd.s64 xb0, %2, 0;\n\t"
      "add.s64 xa1, %1, 2;\n\tadd.s64 xb1, %2, 2;\n\t"
      "add.s64 xa2, %1, 4;\n\tadd.s64 xb2, %2, 4;\n\t"
      "add.s64 xa3, %1, 6;\n\tadd.s64 xb3, %2, 6;\n\t"
      "add.s64 xa4, %1, 1024;\n\tadd.s64 xb4, %2, 64;\n\t"
      "add.s64 xa5, %1, 1026;\n\tadd.s64 xb5, %2, 66;\n\t"
      "add.s64 xa6, %1, 1028;\n\tadd.s64 xb6, %2, 68;\n\t"
      "add.s64 xa7, %1, 1030;\n\tadd.s64 xb7, %2, 70;\n\t"
      "@e tcgen05.mma.cta_group::1.kind::mxf8f6f4.block_scale [%0], xa0, xb0, i0, [%4], [%6], p0;\n\t"
      "@e tcgen05.mma.cta_group::1.kind::mxf8f6f4.block_scale [%0], xa1, xb1, i1, [%4], [%6], pt;\n\t"
      "@e tcgen05.mma.cta_group::1.kind::mxf8f6f4.block_scale [%0], xa2, xb2, i2, [%4], [%6], pt;\n\t"
      "@e tcgen05.mma.cta_group::1.kind::mxf8f6f4.block_scale [%0], xa3, xb3, i3, [%4], [%6], pt;\n\t"
      "@e tcgen05.mma.cta_group::1.kind::mxf8f6f4.block_scale [%0], xa4, xb4, i0, [u1], [v1], pt;\n\t"
      "@e tcgen05.mma.cta_group::1.kind::mxf8f6f4.block_scale [%0], xa5, xb5, i1, [u1], [v1], pt;\n\t"
      "@e tcgen05.mma.cta_group::1.kind::mxf8f6f4.block_scale [%0], xa6, xb6, i2, [u1], [v1], pt;\n\t"
      "@e tcgen05.mma.cta_group::1.kind::mxf8f6f4.block_scale [%0], xa7, xb7, i3, [u1], [v1], pt;\n\t"
      "@e tcgen05.commit.cta_group::1.mbarrier::arrive::one.shared::cluster.b64 [%10];\n\t"
      "@pa tcgen05.commit.cta_group::1.mbarrier::arrive::one.shared::cluster.b64 [%11];\n\t"
      "}"
      ::"r"(d), "l"(adesc), "l"(bdesc), "r"(idesc), "r"(sfa), "l"(sfa_src), "r"(sfb), "l"(sfb_src), "r"(copy_sfb),
        "r"(accum), "r"(bar_empty), "r"(bar_acc), "r"(live)
      : "memory");
}

__device__ __forceinline__ void fc2_stage(uint32_t d, uint64_t adesc, uint64_t bdesc, uint32_t idesc, uint32_t sfa,
    uint64_t sfa_src, uint32_t sfb, uint64_t sfb_src, uint32_t copy_sfb, uint32_t bar_hrel, uint32_t bar_empty,
    uint32_t bar_acc, uint32_t live = 1u) {
  asm volatile(
      "{\n\t.reg .pred e, p0, pt, pc, ph, pl;\n\t.reg .b64 s1, h1, h2;\n\t.reg .b32 j<6>, u1, w1, w2;\n\t"
      ".reg .b64 xa<6>, xb<6>;\n\t"
      "elect.sync _|e, 0xffffffff;\n\tsetp.ne.b32 pl, %12, 0;\n\tand.pred e, e, pl;\n\t"
      "setp.eq.b32 pt, 0, 0;\n\tsetp.eq.b32 p0, 0, 1;\n\tsetp.ne.b32 pc, %8, 0;\n\tsetp.ne.b32 ph, %9, 0;\n\t"
      "and.pred pc, pc, e;\n\tand.pred ph, ph, e;\n\t"
      "@ph tcgen05.commit.cta_group::1.mbarrier::arrive::one.shared::cluster.b64 [%9];\n\t"
      "or.b32 j0, %3, 0;\n\t"
      "or.b32 j1, %3, 536870928;\n\t"
      "or.b32 j2, %3, 1073741824;\n\t"
      "or.b32 j3, %3, 1610612752;\n\t"
      "or.b32 j4, %3, 0;\n\t"
      "or.b32 j5, %3, 536870928;\n\t"
      "add.s64 s1, %5, 32;\n\tadd.u32 u1, %4, 4;\n\t"
      "add.s64 h1, %7, 8;\n\tadd.s64 h2, %7, 16;\n\tadd.u32 w1, %6, 4;\n\tadd.u32 w2, %6, 8;\n\t"
      "@pc tcgen05.cp.cta_group::1.32x128b.warpx4 [%6], %7;\n\t"
      "@pc tcgen05.cp.cta_group::1.32x128b.warpx4 [w1], h1;\n\t"
      "@pc tcgen05.cp.cta_group::1.32x128b.warpx4 [w2], h2;\n\t"
      "@e tcgen05.cp.cta_group::1.32x128b.warpx4 [%4], %5;\n\t"
      "@e tcgen05.cp.cta_group::1.32x128b.warpx4 [u1], s1;\n\t"
      "add.s64 xa0, %1, 0;\n\tadd.s64 xb0, %2, 0;\n\t"
      "add.s64 xa1, %1, 2;\n\tadd.s64 xb1, %2, 2;\n\t"
      "add.s64 xa2, %1, 4;\n\tadd.s64 xb2, %2, 4;\n\t"
      "add.s64 xa3, %1, 6;\n\tadd.s64 xb3, %2, 6;\n\t"
      "add.s64 xa4, %1, 1028;\n\tadd.s64 xb4, %2, 64;\n\t"
      "add.s64 xa5, %1, 1030;\n\tadd.s64 xb5, %2, 66;\n\t"
      "@e tcgen05.mma.cta_group::1.kind::mxf8f6f4.block_scale [%0], xa0, xb0, j0, [%4], [%6], p0;\n\t"
      "@e tcgen05.mma.cta_group::1.kind::mxf8f6f4.block_scale [%0], xa1, xb1, j1, [%4], [%6], pt;\n\t"
      "@e tcgen05.mma.cta_group::1.kind::mxf8f6f4.block_scale [%0], xa2, xb2, j2, [%4], [w1], pt;\n\t"
      "@e tcgen05.mma.cta_group::1.kind::mxf8f6f4.block_scale [%0], xa3, xb3, j3, [%4], [w1], pt;\n\t"
      "@e tcgen05.mma.cta_group::1.kind::mxf8f6f4.block_scale [%0], xa4, xb4, j4, [u1], [w2], pt;\n\t"
      "@e tcgen05.mma.cta_group::1.kind::mxf8f6f4.block_scale [%0], xa5, xb5, j5, [u1], [w2], pt;\n\t"
      "@e tcgen05.commit.cta_group::1.mbarrier::arrive::one.shared::cluster.b64 [%10];\n\t"
      "@e tcgen05.commit.cta_group::1.mbarrier::arrive::one.shared::cluster.b64 [%11];\n\t"
      "}"
      ::"r"(d), "l"(adesc), "l"(bdesc), "r"(idesc), "r"(sfa), "l"(sfa_src), "r"(sfb), "l"(sfb_src), "r"(copy_sfb),
        "r"(bar_hrel), "r"(bar_empty), "r"(bar_acc), "r"(live)
      : "memory");
}
}  // namespace tc
