// Generated by gen_mma_issue.py (agents/moe8). Do not edit by hand.
// One tcgen05 pipeline stage per asm block, one elect.sync.
// Swap-AB: A = weights [2 K-chunks][128 rows][128 B] (SW128), B = tokens, 8-row SW128 atoms.
// A desc: +((kk/4)*16384 + (kk%4)*32)/16 (FC2 k-steps 4, 5 sit at +64 B: chunk 1 starts at k = 64);
// B desc: +((kk/4)*1024 + (kk%4)*32)/16; idesc a_sf_id = b_sf_id = kk%4; SF TMEM += (kk/4)*4.
// Weight-SF sources are 2 x 512 B (desc +32), token-SF images 2 x 128 B (desc +8).
#pragma once
#include <cstdint>
namespace tc {
__device__ __forceinline__ void fc1_stage(uint32_t d, uint64_t adesc, uint64_t bdesc, uint32_t idesc, uint32_t sfa,
    uint64_t sfa_src, uint32_t sfb, uint64_t sfb_src, uint32_t copy_sfb, uint32_t x9, uint32_t bar_empty,
    uint32_t bar_acc) {
  asm volatile(
      "{\n\t.reg .pred e, p0, pt, pc, pa, ph;\n\t.reg .b64 s1, s2;\n\t.reg .b32 i<4>, u1, xsbt;\n\t.reg .b64 xa<8>, xb<8>; .reg .b32 xsa1, xsb1;\n\t"
      "elect.sync _|e, 0xffffffff;\n\t"
      "setp.eq.b32 pt, 0, 0;\n\tsetp.ne.b32 pc, %8, 0;\n\tsetp.ne.b32 pa, %11, 0;\n\t"
      "and.pred pc, pc, e;\n\tand.pred pa, pa, e;\n\t"
      "setp.ne.b32 p0, %9, 0;\n\t"
      "or.b32 i0, %3, 0;\n\t"
      "or.b32 i1, %3, 536870928;\n\t"
      "or.b32 i2, %3, 1073741856;\n\t"
      "or.b32 i3, %3, 1610612784;\n\t"
      "add.s64 s1, %5, 32;\n\tadd.s64 s2, %7, 8;\n\tadd.u32 u1, %4, 4;\n\tadd.u32 xsbt, %6, 4;\n\t"
      "@pc tcgen05.cp.cta_group::1.32x128b.warpx4 [%6], %7;\n\t"
      "@pc tcgen05.cp.cta_group::1.32x128b.warpx4 [xsbt], s2;\n\t"
      "@e tcgen05.cp.cta_group::1.32x128b.warpx4 [%4], %5;\n\t"
      "@e tcgen05.cp.cta_group::1.32x128b.warpx4 [u1], s1;\n\t"
      "add.s64 xa0, %1, 0;\n\tadd.s64 xb0, %2, 0;\n\t"
      "add.s64 xa1, %1, 2;\n\tadd.s64 xb1, %2, 2;\n\t"
      "add.s64 xa2, %1, 4;\n\tadd.s64 xb2, %2, 4;\n\t"
      "add.s64 xa3, %1, 6;\n\tadd.s64 xb3, %2, 6;\n\t"
      "add.s64 xa4, %1, 1024;\n\tadd.s64 xb4, %2, 64;\n\t"
      "add.s64 xa5, %1, 1026;\n\tadd.s64 xb5, %2, 66;\n\t"
      "add.s64 xa6, %1, 1028;\n\tadd.s64 xb6, %2, 68;\n\t"
      "add.s64 xa7, %1, 1030;\n\tadd.s64 xb7, %2, 70;\n\t"
      "add.u32 xsa1, %4, 4;\n\tadd.u32 xsb1, %6, 4;\n\t"
      "@e tcgen05.mma.cta_group::1.kind::mxf8f6f4.block_scale [%0], xa0, xb0, i0, [%4], [%6], p0;\n\t"
      "@e tcgen05.mma.cta_group::1.kind::mxf8f6f4.block_scale [%0], xa1, xb1, i1, [%4], [%6], pt;\n\t"
      "@e tcgen05.mma.cta_group::1.kind::mxf8f6f4.block_scale [%0], xa2, xb2, i2, [%4], [%6], pt;\n\t"
      "@e tcgen05.mma.cta_group::1.kind::mxf8f6f4.block_scale [%0], xa3, xb3, i3, [%4], [%6], pt;\n\t"
      "@e tcgen05.mma.cta_group::1.kind::mxf8f6f4.block_scale [%0], xa4, xb4, i0, [xsa1], [xsb1], pt;\n\t"
      "@e tcgen05.mma.cta_group::1.kind::mxf8f6f4.block_scale [%0], xa5, xb5, i1, [xsa1], [xsb1], pt;\n\t"
      "@e tcgen05.mma.cta_group::1.kind::mxf8f6f4.block_scale [%0], xa6, xb6, i2, [xsa1], [xsb1], pt;\n\t"
      "@e tcgen05.mma.cta_group::1.kind::mxf8f6f4.block_scale [%0], xa7, xb7, i3, [xsa1], [xsb1], pt;\n\t"
      "@e tcgen05.commit.cta_group::1.mbarrier::arrive::one.shared::cluster.b64 [%10];\n\t"
      "@pa tcgen05.commit.cta_group::1.mbarrier::arrive::one.shared::cluster.b64 [%11];\n\t"
      "}"
      ::"r"(d), "l"(adesc), "l"(bdesc), "r"(idesc), "r"(sfa), "l"(sfa_src), "r"(sfb), "l"(sfb_src), "r"(copy_sfb),
        "r"(x9), "r"(bar_empty), "r"(bar_acc)
      : "memory");
}

__device__ __forceinline__ void fc2_stage(uint32_t d, uint64_t adesc, uint64_t bdesc, uint32_t idesc, uint32_t sfa,
    uint64_t sfa_src, uint32_t sfb, uint64_t sfb_src, uint32_t copy_sfb, uint32_t x9, uint32_t bar_empty,
    uint32_t bar_acc) {
  asm volatile(
      "{\n\t.reg .pred e, p0, pt, pc, pa, ph;\n\t.reg .b64 s1, s2;\n\t.reg .b32 i<4>, u1, xsbt;\n\t.reg .b64 xa<6>, xb<6>; .reg .b32 xsa1, xsb1;\n\t"
      "elect.sync _|e, 0xffffffff;\n\t"
      "setp.eq.b32 pt, 0, 0;\n\tsetp.ne.b32 pc, %8, 0;\n\tsetp.ne.b32 pa, %11, 0;\n\t"
      "and.pred pc, pc, e;\n\tand.pred pa, pa, e;\n\t"
      "setp.eq.b32 p0, 0, 1;\n\tsetp.ne.b32 ph, %9, 0;\n\tand.pred ph, ph, e;\n\t"
      "@ph tcgen05.commit.cta_group::1.mbarrier::arrive::one.shared::cluster.b64 [%9];\n\t"
      "or.b32 i0, %3, 0;\n\t"
      "or.b32 i1, %3, 536870928;\n\t"
      "or.b32 i2, %3, 1073741856;\n\t"
      "or.b32 i3, %3, 1610612784;\n\t"
      "add.s64 s1, %5, 32;\n\tadd.s64 s2, %7, 8;\n\tadd.u32 u1, %4, 4;\n\tadd.u32 xsbt, %6, 4;\n\t"
      "@pc tcgen05.cp.cta_group::1.32x128b.warpx4 [%6], %7;\n\t"
      "@pc tcgen05.cp.cta_group::1.32x128b.warpx4 [xsbt], s2;\n\t"
      "@e tcgen05.cp.cta_group::1.32x128b.warpx4 [%4], %5;\n\t"
      "@e tcgen05.cp.cta_group::1.32x128b.warpx4 [u1], s1;\n\t"
      "add.s64 xa0, %1, 0;\n\tadd.s64 xb0, %2, 0;\n\t"
      "add.s64 xa1, %1, 2;\n\tadd.s64 xb1, %2, 2;\n\t"
      "add.s64 xa2, %1, 4;\n\tadd.s64 xb2, %2, 4;\n\t"
      "add.s64 xa3, %1, 6;\n\tadd.s64 xb3, %2, 6;\n\t"
      "add.s64 xa4, %1, 1028;\n\tadd.s64 xb4, %2, 64;\n\t"
      "add.s64 xa5, %1, 1030;\n\tadd.s64 xb5, %2, 66;\n\t"
      "add.u32 xsa1, %4, 4;\n\tadd.u32 xsb1, %6, 4;\n\t"
      "@e tcgen05.mma.cta_group::1.kind::mxf8f6f4.block_scale [%0], xa0, xb0, i0, [%4], [%6], p0;\n\t"
      "@e tcgen05.mma.cta_group::1.kind::mxf8f6f4.block_scale [%0], xa1, xb1, i1, [%4], [%6], pt;\n\t"
      "@e tcgen05.mma.cta_group::1.kind::mxf8f6f4.block_scale [%0], xa2, xb2, i2, [%4], [%6], pt;\n\t"
      "@e tcgen05.mma.cta_group::1.kind::mxf8f6f4.block_scale [%0], xa3, xb3, i3, [%4], [%6], pt;\n\t"
      "@e tcgen05.mma.cta_group::1.kind::mxf8f6f4.block_scale [%0], xa4, xb4, i0, [xsa1], [xsb1], pt;\n\t"
      "@e tcgen05.mma.cta_group::1.kind::mxf8f6f4.block_scale [%0], xa5, xb5, i1, [xsa1], [xsb1], pt;\n\t"
      "@e tcgen05.commit.cta_group::1.mbarrier::arrive::one.shared::cluster.b64 [%10];\n\t"
      "@pa tcgen05.commit.cta_group::1.mbarrier::arrive::one.shared::cluster.b64 [%11];\n\t"
      "}"
      ::"r"(d), "l"(adesc), "l"(bdesc), "r"(idesc), "r"(sfa), "l"(sfa_src), "r"(sfb), "l"(sfb_src), "r"(copy_sfb),
        "r"(x9), "r"(bar_empty), "r"(bar_acc)
      : "memory");
}
}  // namespace tc
